### ISSUE TITLE
Document's xml string implementation

### ISSUE THREAD

**Issue by ivensdenner** [tadija/AEXML#103]
Why the Document's [xml string](https://github.com/tadija/AEXML/blob/28599f78f89bc188de02d2e3b8b14a1c75a2e1c3/Sources/Document.swift#L120-L126) concatenates all it's children's string? Wouldn't be better it return just the root's string after the header, since a xml file with more than one root is a invalid xml document?

Even if the programmer make a mistake and add two or more elements "as roots" to the document, I think this error shouldn't be propagated. I mean, it's weird that this property can return an invalid XML without any hint of failure.

**Comment by tadija** [comment]
Good point!

**Comment by tadija** [comment]
This is now fixed in PR #104 so this issue can be closed, thanks for helping.
