### ISSUE TITLE
Supporting Objective-C

### ISSUE THREAD

**Issue by vicng** [tadija/AEXML#112]
My library uses AEXML as a dependency, but it supports both Swift and Obj-C. The problem is that any exposed API methods in my library that use AEXML cannot be exported into Obj-C.

To fix this, I've created a pull request to add Obj-C support to AEXML (https://github.com/tadija/AEXML/pull/111). The only significant change to existing Swift API would be that AEXML Options needs to be declared as a class instead of a struct.

Please let me know if this is something you'd be willing to add! If not, I will unfortunately need to switch out to an XML library that supports both Swift/Obj-C.

**Comment by tadija** [comment]
Hi @vicng, thanks for this. 

I thought about it and decided to move on without support for Objective-C.
Reason is that I'd like to keep moving forward with Swift and perhaps have a better support for Linux.

In your case (or similar) there are still some Obj-C XML parsers which you could use.

Cheers
