### ISSUE TITLE
Q. Random Access within XML?

### ISSUE THREAD

**Issue by SuperWomble** [tadija/AEXML#113]
Hi. Not an issue, so much as a question of usage/capability.

I'm working with SVG files. A typical file contains any number of <g> tags, all nested in any number of arrangements with other tags.  e.g. 

```
<?xml version="1.0" encoding="UTF-8"?>
<svg ...>
	<defs>
            <path ... </path>
            <path ... </path>
    </defs>
    <g ...>
        <g ...>
			<path ...</path>
			<path ...</path>
			<path ...</path>
            <g ...>
   				<path ...</path>
				<path ...</path>
                <g id="pick_me">
                    <use ...</use>
                    <use someAttribute="PICK_ME_PICK_ME"</use>
                </g>
            </g>
        </g>
    </g>
</svg>
```
I'm sorry for the verbosity, but hopefully you get the idea: the overall structure is convoluted and unknown at build-time.

Q. is there a facility in AEXML to find an element that contains a specific attribute? In this case, the parent <g> that contains a <use> tag with the attribute "PICK_ME_PICK_ME"?

e.g. a way to firstly find the tag with the attribute, and then the parent element?

Or would I somehow need to iterate through all children, to find the elements? (And if so, would you recommend a particular usage-pattern of AEXML for this?)

I've looked through the unit tests, but haven't seen a random-access example.

Thanks for all your hard work on this project. Cheers.

**Comment by SuperWomble** [comment]
I was able to solve this issue using AEXML and noahcgreen's changes. Cheers to you both.

**Comment by tadija** [comment]
Great, then I'll close this one!
