### ISSUE TITLE
Why is AEXMLElement.all not nil-able?

### ISSUE THREAD

**Issue by hohl** [tadija/AEXML#12]
It would be nice to be able to use `all` in a way like that:

    for element in parent.all {
    }

This will work already, but if there are *zero* elements, it should get called with `self`. So I wondered why `all` isn't nil-able already. Returning `self` of course makes sense for many functions of this library, I understand, but I don't see any sense in returning `self` in all too.

I also noticed that there is a small inconsistence about it in the library: `AEXMLElement.allWithAttributes` is nil-able, while `AEXMLElement.all` is not.

**Comment by tadija** [comment]
Hello,

I agree and this is changed in last commit - `all` property is now optional.
As a metter of fact, I did it also with `last` property and added a `first` property in a same way too.
