### ISSUE TITLE
Value of optional type not unwrapped; did you mean to use '!' or '?'?

### ISSUE THREAD

**Issue by nehoox** [tadija/AEXML#121]
Hi,
a probleme appear : 

self.document.root["Document"]["Exemple"].int
self.document.root["Document"]["Exemple"].bool
self.document.root["Document"]["Exemple"].double,
xcode warn me : Value of optional type 'Bool?' not unwrapped; did you mean to use '!' or '?'?

this 3 methods return me nil 

would you have a solution ?

**Comment by tadija** [comment]
Yes, you just need to unwrap those optional properties... :)
