### ISSUE TITLE
about cdata

### ISSUE THREAD

**Issue by alkincakiralar1996** [tadija/AEXML#123]
hello i am new swift developer i need some idea or help that i can fix this problem

    <theme type="text" name=".BASLIK"><![CDATA[ color: #000000; font-size: 40px; font-family: 'Arial'; text-align: center; vertical-align: middle; font-weight: normal; font-style: none; text-decoration: none; display: table-cell;]]></theme> 

its writing like this on xml file

 color: #000000; font-size: 40px; font-family: 'Arial'; text-align: center; vertical-align: middle; font-weight: normal; font-style: none; text-decoration: none; display: table-cell;

its come with like this

how can i take this data to append an array like 

arraytitles[0] = 'color'
arraytitles[1] = 'font-size'

arrayresult[0] = '#000000'
arrayresult[1] = '40px'

how can i do it that what i looks like ?

**Comment by tadija** [comment]
Hi @alkincakiralar1996,

CDATA is still not supported in this version of library (check out issue #101), you might wanna try version from PR #119 if that helps you.

Cheers,
// T
