### ISSUE TITLE
Does AEXML.swift works exactly as Element.swift?

### ISSUE THREAD

**Issue by vaibhiarora** [tadija/AEXML#124]
Does the file AEXML.swift (https://github.com/tadija/AEXML/blob/973a1f5fd40abba5d4457e2b54f587a0d7d4cd0d/Source/AEXML.swift) works exactly as the Element.swift(https://github.com/tadija/AEXML/blob/master/Sources/Element.swift)?

Or is there some other file which works same as AEXML.swift?

**Comment by tadija** [comment]
In some update AEXML was refactored into multiple source files, before that everything was in AEXML.swift, but after all that same code was migrated to separate sources (all of them).
