### ISSUE TITLE
Build error: `error: instance member 'document' cannot be used on type`

### ISSUE THREAD

**Issue by rahul-malik** [tadija/AEXML#133]
```
Sources/Parser.swift:18:20: error: instance member 'document' cannot be used on type 'AEXMLParser'
        let trim = document.options.parserSettings.shouldTrimWhitespace
                   ^~~~~~~~
```

It appears this regression was added recently in this commit:
https://github.com/tadija/AEXML/commit/506c15df3160f720b58b543fa7b42226e21e1463

**Comment by tadija** [comment]
Thanks for reporting @rahul-malik, I've just fixed that in 8f9bd2859151a36882d8085a617e4cf95cdebeeb

**Comment by Daltron** [comment]
@tadija Could you possibly release a new version with this fix please? It would be greatly appreciated! I'm using a dependency that uses this as a dependency.

**Comment by Bitwix** [comment]
+1 for comment by @Daltron - we use this via a released version

**Comment by tadija** [comment]
Sure, no problem, I've released 4.2.2 now.

**Comment by Daltron** [comment]
@tadija Thanks a bunch! 👍 👍 👍

**Comment by Bitwix** [comment]
Thanks from me too - it's a great help
