### ISSUE TITLE
Excluded space prefix before utf8 character

### ISSUE THREAD

**Issue by Kalvin126** [tadija/AEXML#137]
I have an XML with an entry 
```XML
<string name="test_key_with_utf">test &#8230;</string>
```

With AEXML 4.0.X, this returned `test …`, but updating to `4.2.2` it now returns `test…`. Note that it is different in that there no space between `test` and `…`.

**Comment by tadija** [comment]
Hi, please check if that's maybe related to #114, if it is you may configure this with `AEXMLOptions`.

**Comment by Kalvin126** [comment]
Seems so! setting `shouldTrimWhitespace = false` made my tests pass again. The space should not even be considered part of the utf character to trim though.

**Comment by tadija** [comment]
Yeah, well, maybe this setting should have been `false` by default, I wasn't really sure how it behaved before #114.
