### ISSUE TITLE
Huge memory usage with base64 strings in xml.

### ISSUE THREAD

**Issue by Clanat** [tadija/AEXML#141]
1. Create an XML base64 data.
2. Create AEXMLDocument

For example in my project I've received xml with ~ 3mb file encoded in base64 string. Parse it consumes ~ 1gb ram. Of course I had app crash.

**Comment by tadija** [comment]
Hi @Clanat, are you using the latest version? Could this be somehow related to #117 ?

**Comment by Clanat** [comment]
I'm using `pod 'AEXML', '~> 4.1.0'`. I think it's related with xml parsing.

**Comment by tadija** [comment]
Well please try the latest version (4.2.2), as this was probably fixed with #117.
