### ISSUE TITLE
error: product dependency 'AEXML' not found

### ISSUE THREAD

**Issue by twobitunicorn** [tadija/AEXML#151]
When I have a dependency on AEXML, I get the error that the dependency is not found.  Here is my dependency bit 
``` .package(url: "https://github.com/tadija/AEXML.git", .upToNextMajor(from: "4.3.2"))```.

It seems to clone and build it, but the linking is getting into a pickle.  I do have a target with a dependency on AEXML. 
```        
.target(
/** Some Target */
name: "MyTarget",
dependencies: ["AEXML"]),
```
Other dependencies I have work fine.  Anybody have some insight into this?  Thank you!

**Comment by drekka** [comment]
Just came across this and have a fix: I've found this same problem in a couple of dependencies. It appears SPM is getting picking and throws an error if it cannot find a Products section in the dependencies Package.swift. AEXML is missing this section. 

How to fix until AEXML is patched:

1. Use `swift package edit AEXML` to place the package in edit mode. This will move it to the /Packages directory and unlock it. 
1. Edit the Package.swift file and insert the products section like this

```
let package = Package(
    name: "AEXML",
    products: [
        .library(name: "AEXML", targets: ["AEXML"]),
        ],
   dependencies: [], 
```

`swift package generate-xcodeproj` should now work.

**Comment by tadija** [comment]
Thanks for explaining this @drekka, it's now fixed with #152.

**Comment by drekka** [comment]
Thanks got it.

**Comment by twobitunicorn** [comment]
@drekka ya, thanks! Make sense.
