### ISSUE TITLE
Differentiate <error> and element <error> not found

### ISSUE THREAD

**Issue by Gurpartap** [tadija/AEXML#16]
```swift
let dataString1 = "<?xml version='1.0' encoding='utf-8'?><results><error>No entry for today</error></results>"
let dataString2 = "<?xml version='1.0' encoding='utf-8'?><results><entry>Some entry</entry></results>"

let data = dataString1.dataUsingEncoding(NSUTF8StringEncoding)

var xmlError: NSError?
if let xmlDoc = AEXMLDocument(xmlData: data!, error: &xmlError) {
    let errorTag = xmlDoc.root["error"]
    
    // always going to be true
    if xmlDoc.root["error"].name == "error" {
        let e = NSError(domain: "...", code: 101, userInfo: [NSLocalizedDescriptionKey: errorTag.stringValue])
        return onFailure(error: e)
    }
    
    // never gets to here...
}
```

When dataString1 is used, the code above behaves as expected. `<error>` tag is determined as "error" and handled as such.

When dataString2 is used, the above fails to find `<error>` tag in the data and the check omits `element "error" not found` "error".

There seems to be no way to distinguish between actual `<error>` tag and missing `<error>` tag unless I just make an exception for stringValue == `element <error> not found`.

I think that existence of `<error>` should not be handled inside AEXML. Or at least not be the same kind of error as is when `xmlDoc.root["error"].name` returns "error".

Checking for existence of `<error>` tag should be with a != instead of ==.

Should allow you to do `xmlDoc.root["error"].name != "error"` instead of the current `xmlDoc.root["error"].name == "error"`.

**Comment by tadija** [comment]
I think that the best solution is just to 'namespace' internal error element in AEXML, so it's called 'AEXMLError' instead of 'error', and this could not happen in that case, do you agree?

**Comment by Gurpartap** [comment]
AEXMLError sounds better alternative for errors pertaining to parsing or writing XML. But that's a different issue.

I think AEXML should not be bothered to check for `<error>` in the XML. Let the end-developer think about what goes in the XML content.

**Comment by Gurpartap** [comment]
I now see how AEXMLError is related to this issue and hard to separate since at the moment AEXML returns any error in the form of `AEXMLElement("error", ..)`.

**Comment by Gurpartap** [comment]
For the time being, I'm using:
```swift
if xmlDoc.root["error"].name == "error" && xmlDoc.root["error"].stringValue != "element <error> not found" {
    ...
}
```

**Comment by tadija** [comment]
Hi, this is fixed.

Now you have `errorElementName` class property on `AEXMLElement`,
so you can check against it if some element doesn't exist, and parse <error> element like any other.

Thanks for the feedback,
// T
