### ISSUE TITLE
module compiled with Swift 5.0 cannot be imported by the Swift 5.1 compiler.

### ISSUE THREAD

**Issue by GirishBodhe** [tadija/AEXML#160]
module compiled with Swift 5.0 cannot be imported by the Swift 5.1 compiler: *******AEXML.framework/Modules/AEXML.swiftmodule/x86_64.swiftmodule

**Comment by GirishBodhe** [comment]
> module compiled with Swift 5.0 cannot be imported by the Swift 5.1 compiler: *******AEXML.framework/Modules/AEXML.swiftmodule/x86_64.swiftmodule

can you please update it ASPA.

**Comment by GirishBodhe** [comment]
> > module compiled with Swift 5.0 cannot be imported by the Swift 5.1 compiler: *******AEXML.framework/Modules/AEXML.swiftmodule/x86_64.swiftmodule
> 
> can you please update it ASPA.

As i am using Xcode 11.0

**Comment by tadija** [comment]
AEXML doesn't have to be updated for this, instead you should just rebuild your dependencies with the new Xcode 11.
