### ISSUE TITLE
module compiled with Swift 5.1 cannot be imported by the Swift 5.1.2 compiler

### ISSUE THREAD

**Issue by GirishBodhe** [tadija/AEXML#164]
Please upgrade it to Swift 5.1.2

**Comment by GirishBodhe** [comment]
Can you do the needful for the same.
Thanks in advance.

**Comment by GirishBodhe** [comment]
Can you do the needful for the same.

**Comment by artrmz** [comment]
Using Carthage? Just rebuild it with new Xcode. There should be no code changes needed to make it work with 5.1.2

**Comment by GirishBodhe** [comment]
> Using Carthage? Just rebuild it with new Xcode. There should be no code changes needed to make it work with 5.1.2

tried with using Carthage and build it in Xcode Version 11.2.1 then also i am getting the sane issue **"module compiled with Swift 5.1 cannot be imported by the Swift 5.1.2 compiler"**

**Comment by GirishBodhe** [comment]
Can you do the needful for the same.

**Comment by GirishBodhe** [comment]
> Using Carthage? Just rebuild it with new Xcode. There should be no code changes needed to make it work with 5.1.2

Thanks it worked..
