### ISSUE TITLE
module compiled with Swift 5.1 cannot be imported by the Swift 5.1.2 compiler

### ISSUE THREAD

**Issue by GirishBodhe** [tadija/AEXML#165]

**Comment by GirishBodhe** [comment]
Can you do the needful for the same.

**Comment by GirishBodhe** [comment]
sorry for interrupt please close these issue..it has been resolve.

**Comment by TheMadOne** [comment]
I believe this is a swift issue, not a AEXML issue. So, I think it can be closed.

**Comment by tadija** [comment]
Agreed.
