### ISSUE TITLE
Add child with end tag

### ISSUE THREAD

**Issue by evanxlh** [tadija/AEXML#167]
How to add child with end tag? 

eg. I want to add **Category** node, and also end with **</Category>**.

```
<root>
<Category name: 'category'></Category>
</root>
```

**Comment by tadija** [comment]
it seems that you need to have a value for this node in order to generate the end tag too:

```swift
let doc = AEXMLDocument()
doc.addChild(name: "Category", value: "Test")
print(doc.xml) // <Category>Test</Category>
```
