### ISSUE TITLE
Build Target out of date

### ISSUE THREAD

**Issue by PhilStollery** [tadija/AEXML#172]
Warning when building for the latest version of Swift and Xcode 12. 

Showing Recent Messages
The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99.

**Comment by silviagaluzzi** [comment]
same here, and I have this error compiling my project with XCode12 beta:

*** Building scheme "AEXML iOS" in AEXML.xcodeproj
Build Failed
	Task failed with exit code 1:
	/usr/bin/xcrun lipo -create ../Caches/org.carthage.CarthageKit/DerivedData/12.0_12A8169g/AEXML/4.5.0/Build/Intermediates.noindex/ArchiveIntermediates/AEXML\ iOS/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/AEXML.framework/AEXML ../Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A8169g/AEXML/4.5.0/Build/Products/Release-iphonesimulator/AEXML.framework/AEXML -output ../proj/Apps-08.04/Lib/Carthage/Build/iOS/AEXML.framework/AEXML

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/1c/sdgfpmvs1k94y46pnhw0ykm40000gp/T/carthage-xcodebuild.ZLQalf.log

**Comment by tadija** [comment]
Hi, this should be fixed in the latest release (4.6.0).
