### ISSUE TITLE
AEXML.modulemap not found on iOS 14

### ISSUE THREAD

**Issue by BBTMathison** [tadija/AEXML#173]
Using Xcode 12.0 (beta 4), I get this compile error.  This is building to the simulator.

When I build from Xcode beta to my phone, which is still on iOS 13 - it works fine.

**Comment by HsS-2019** [comment]
oh i meet the same problem. it seem as the range of supported deployment target versions is 9.0 to 14.0.99 in Xcode 12. when this framework deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is still set to 8.0.

**Comment by HsS-2019** [comment]
i can't find the  build setting called "VALID_ARCHS" in my project. it seem like the "Architectures" of build setting

**Comment by HsS-2019** [comment]
ok maybe it's wrong, cause i still can not build this framework for Xcode 12

**Comment by HsS-2019** [comment]
hi bro, maybe [this issure](https://github.com/Carthage/Carthage/issues/3019) can inspire you

**Comment by HsS-2019** [comment]
> hi bro, maybe [this issure](https://github.com/Carthage/Carthage/issues/3019) can inspire you

yeah, it work for me!

**Comment by tadija** [comment]
Hi, this should be fixed in the latest release (4.6.0).
