### ISSUE TITLE
Xcode 12 build warning - 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0

### ISSUE THREAD

**Issue by gabors** [tadija/AEXML#174]
Hi when building with Xcode 12 GM I get this build warning

The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99.

Looking at the framework  project file it does indeed specify 8.0

Will there be a framework update?
I'm integrating using SPM.

Thanks in advance!

**Comment by tadija** [comment]
Hi, this should be fixed in the latest release (4.6.0).
