### ISSUE TITLE
Ability to exclude standalone attribute from document header

### ISSUE THREAD

**Issue by sskjames** [tadija/AEXML#179]
First of all, thank you very much for this library. 
I observed that the attribute "standalone=yes/no" is added to the document header.
`<?xml version="1.0" encoding="utf-8" standalone="no"?>`
I checked the source code and it looks like there is no option to prevent this attribute from being written to the final xml string.
Is it possible? I would like to have it this way:
`<?xml version="1.0" encoding="utf-8"?>`
Unfortunately, I'm generating a xml file which would be consumed by another application and the integration doesn't work when the "standalone" attribute is included in the document header.

**Comment by tadija** [comment]
Hi @sskjames, you could override `xml` property of `AEXMLDocument` and use a custom header like this:

```swift
open override var xml: String {
    var xml =  "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n"
    xml += root.xml
    return xml
}
```

**Comment by sskjames** [comment]
Thanks @tadija for the swift response. I'll try that out.

**Comment by sskjames** [comment]
It worked. Thanks for the help.
