### ISSUE TITLE
Compile error with Swift 1.2 - "'?' must be followed by a call, member lookup, or subscript"

### ISSUE THREAD

**Issue by dmcgloin** [tadija/AEXML#18]
AEXML.swift:119:42: '?' must be followed by a call, member lookup, or subscript

    private var parentsCount: Int {
        var count = 0
        var element = self
        while let parent = element.parent? {
            count++
            element = parent
        }
        return count
    }

**Comment by nabil-takla** [comment]
I have the same issue

**Comment by tadija** [comment]
This is now fixed on branch 'xcode-6.3-beta-4'.
I'll merge this on 'master' branch when Xcode 6.3 is out of beta.

**Comment by appsird** [comment]
Swift 1.2 is now out of beta.. recommend to place this fix on master branch

**Comment by appsird** [comment]
Though, when I include this update I receive an error:

: '[AEXMLElement]?' does not have a member named 'Generator'

Where I use the construct:

      for tour in xml["index"]["tour"].all {

seems to no longer like the .all

**Comment by appsird** [comment]
I was able to avoid this error by using instead:

 for tour in xml["index"]["tour"].all! 

And in general had to sprinkle forced unwrapping operators to many derivative items, e.g.

mediaURL = NSURL(string: d.value!)

**Comment by tadija** [comment]
Yes, well `all` property is a optional so this is how it should work.

Anyway, this is now merged on master branch so this issue is fixed.
