### ISSUE TITLE
3 unit tests fail in example project under Xcode 6.1.1 (6A2006)

### ISSUE THREAD

**Issue by dmcgloin** [tadija/AEXML#20]
Without any changes, after downloading latest code, 3 unit tests fail:

testChildrenElements()
testAllElements()
testLastElement()

I was actually trying to debug an issue with Xcode 6.3 Beta, but then I realized that I could not get the tests to run without crashing. However, I had to make 1 change to get code to compile, so I thought maybe my change caused the failure.

However, then I went back to Xcode 6.1.1 and am seeing these 3 test failures.

Will submit separate issue for the Xcode 6.3 beta.

**Comment by tadija** [comment]
This is now fixed with latest merge so I'll close this issue, thanks for the feedback.
