### ISSUE TITLE
Unit tests crash in example project under Xcode 6.3 Beta 1 (6D520o)

### ISSUE THREAD

**Issue by dmcgloin** [tadija/AEXML#21]
I know it may not be appropriate to note issues found using Xcode beta, but I thought I would submit this anyway.

The code compiles after a couple minor changes. But it crashes when running the tests.

After some debugging, it looks like this is related to the issue described here:

http://stackoverflow.com/questions/28487142/delegate-methods-not-called-if-implementing-class-is-marked-private

For Swift 1.2, it also looks like the NSXMLParserDelegate function declarations have changed slightly, which may also have been causing the delegate functions to be called.

**Comment by tadija** [comment]
This is now fixed on branch 'xcode-6.3-beta-4'.
I'll merge this on 'master' branch when Xcode 6.3 is out of beta.

Btw, it seems like a bug to me that delegate functions are not called when they're inside a private class.
I wrote a few more details about that [here](http://stackoverflow.com/a/28831745/2165585).

**Comment by tadija** [comment]
Unfortunatelly, delegate functions are still not called when inside a private class so it has to be internal.

Anyway, this is now merged on master branch so this issue is fixed.
