### ISSUE TITLE
Using a variable with .allWithAttributes

### ISSUE THREAD

**Issue by eccsp** [tadija/AEXML#24]
Is there a way to pass a variable extract the following? or maybe there's another simple way of doing this.

var theColor = "yellow"
xmlDoc.root["cats"]["cat"].allWithAttributes(["breed" : "Domestic", "color" : "\\(theColor)"])
or
xmlDoc.root["cats"]["cat"].allWithAttributes(["breed" : "Domestic", "color" : theColor"])

var theInt = 44
xmlDoc.root["event"]["date"].allWithAttributes(["event" : theInt])) 
xmlDoc.root["event"]["date"].countWithAttributes(["event" : theInt]))

**Comment by tadija** [comment]
It's just a regular `[NSObject : AnyObject]` dictionary.

You can do it like this:

```swift
var theColor = "yellow"
xmlDoc.root["cats"]["cat"].allWithAttributes(["breed" : "Domestic", "color" : theColor])
```

**Comment by eccsp** [comment]
Unfortunately it doesn't work as suggested;
Type 'String' does not conform to protocol 'AnyObject'

**Comment by tadija** [comment]
I don't have time to go deep into this now, but can you try this workaround:

```swift
var theKey = "color" as NSObject
var theValue = "yellow" as NSObject
let theAttributes = [theKey : theValue]
if let cats = xmlDoc.root["cats"]["cat"].allWithAttributes(theAttributes) {
    // do something
}
```

Casting key and value to NSObject should get rid of that compiler error, I know it's not perfect but it's a start.

**Comment by angerthosenear** [comment]
Taking this a step further, I'm trying to overwrite an element if my new node matches an attribute.
```swift
let date = "date" as NSObject
let dateFor = (xmlDoc.root.attributes["date"] as! String) as NSObject
let theAttributes = [date: dateFor]

let newEntry = xmlToWrite.root

if var entry = xmlDoc.allWithAttributes(theAttributes){
    entries = [entryToWrite] //there will only ever be 1
}
//else it will just add a child element
```
xmlDoc.root has multiple attributes (the other being an entered date), so I cannot just snag all of them to plug into the allWithAttributes.

I feel like it's close and I'm just missing something here.

Thanks for your help.

**Comment by pyanfield** [comment]
I have the same problems,casting the value to NSObject works for me.
