### ISSUE TITLE
AEXMLParser handles didEndElement Call wrong

### ISSUE THREAD

**Issue by ussu99** [tadija/AEXML#25]
An Xml like the following one will result in wrong Value for the Element **version**:
`<Document><version>1.0</version>\n\t</Document>`

Current Implementation produces for the Element with Name **version**  value "1.0\n\t" which is wrong.
Expected Value should be "1.0"
 
Current implementation should be changed to:

	func parser(parser: NSXMLParser!, didEndElement elementName: String!, namespaceURI: String!, qualifiedName qName: String!) {
		currentParent = currentParent?.parent
		currentValue = String()
		currentElement = nil
	}

**Comment by tadija** [comment]
Ok, thanks, this is fixed now.
