### ISSUE TITLE
AEXML crashes in XCode 6.3.1

### ISSUE THREAD

**Issue by msayeed78** [tadija/AEXML#27]
Hi, Before upgrading to latest version of xcode 6.3.1. AEXML was working perfectly. But after upgrade it is crashing.  below is the error message.

Optional("XML Document must have root element.")
nil
fatal error: Array index out of range

please fix this issue as soon as possible because my project depends on this.

Thanks & Regards
Sayeed.

**Comment by tadija** [comment]
I don't have any build error after updating Xcode to 6.3.1, so you better check if you have the latest version of AEXML, or is everything ok with your code.

**Comment by msayeed78** [comment]
Thank you very much for your early response. Now it is working fine after using the latest version of AEXML.
