### ISSUE TITLE
Write XML overwriting last element

### ISSUE THREAD

**Issue by gabriel-jones** [tadija/AEXML#28]
I'm trying to add a new element to an xml doc like so:
```
 if let document = AEXMLDocument(xmlData: data, error: &error) {
    let attributes = ["location": fishData.location]
    let fish = document["FISHDICT"].addChild(name: "FISH", attributes: attributes)
```
But this overwrites the last element in the document. Am I doing something wrong?

**Comment by tadija** [comment]
I have added new test in AEXMLTests (testAddChildWithAttributes), so you should check that and fix your code.
