### ISSUE TITLE
Remove child feature?

### ISSUE THREAD

**Issue by angerthosenear** [tadija/AEXML#30]
I notice the lack of a remove child feature. Are there any plans for this to incorporated in the future? Or some mostly simply way of doing it (like set an element to nil or something)?

Thanks!

**Comment by angerthosenear** [comment]
As a workaround for the current lack of this feature, and for overwriting a child:
1. Convert the child you want to replace to a string with `.xmlStringCompact`
2. Same as (1) but with your new element
3. Convert your whole old AEXMLDocument to a string yet again with `.xmlStringCompact`
4. `let newDoc = oldDoc.stringByReplacingOccurrencesOfString(oldElement, withString: newElement)`
5. Convert your newDoc back into an AEXMLDocument and continue

**Comment by tadija** [comment]
Hello,

it was originally created only for reading and writing XML, so it never crossed my mind that someone would use this to modify XML dynamically, but what the heck, I've added `removeFromParent()` method to `AEXMLElement` so now it can do that too, just pull the latest version.

Cheers,
// T

**Comment by angerthosenear** [comment]
Perfect!

Thank you so much, certainly more streamlined than my string replacement method. Thanks for the fast update.

-atn
