### ISSUE TITLE
Add prependChild feature

### ISSUE THREAD

**Issue by angerthosenear** [tadija/AEXML#33]
Following up with previous feature request, would it be possible to prepend a Child element? I'm currently using my string replacement method to do this.

I know prepending a Child is a rarely used feature, but I would greatly appreciate it.

Thanks again,
atn

__
Update
__

Ended up changing some of my code around, so you can skip on doing this if you want since it would be so rarely used.

**Comment by tadija** [comment]
As you said, I also find this very rarely used feature, so I would rather skip implementing that.
