### ISSUE TITLE
Parsing XML with namespaces

### ISSUE THREAD

**Issue by ajsait** [tadija/AEXML#34]
Currently, there is no way to set the XMLParser shouldProcessNamespaces to true. So when accessing an element, the complete tagname with namespace needs to be passed. e.g xml["f:animal"] instead of just xml["animal"]

**Comment by tadija** [comment]
Unfortunately, this is currently not supported by AEXML as it is "not robust full featured XML parser (at the moment)". :)

This kind of addition would probably require a bit more work then just adding `shouldProcessNamespaces` property somewhere, like adding namespace property to AEXMLElement, covering that with unit tests, docs and maybe even some more logic (I don't have much experience with namespaces in XML so not sure what else is there important).

If somebody would like to contribute in that direction, be my guest.

**Comment by vincentfaller** [comment]
I did a pull request that will allow for excluded namespaces.

**Comment by tadija** [comment]
Support for this is added in latest (2.1.0) version.
