### ISSUE TITLE
.all! returns an element whose parent is nil

### ISSUE THREAD

**Issue by misbell** [tadija/AEXML#41]
for example in my xml

 var x = anelement["attrib"]["attrib"] 
returns an AEXMLElement with a good parent

var x = someelements["attrib"]["attrib"].all!
returns some AEXMLElements but each with parent=nil

that cost me a lot of hours today :-1:

**Comment by tadija** [comment]
I could not reproduce this bug but I've also added test for this (which passes).
If you want to contribute a little bit more, please make some example which shows this bug in effect.
