### ISSUE TITLE
Swift 2.0 Xcode 7.0 iOS 9

### ISSUE THREAD

**Issue by nabil-takla** [tadija/AEXML#48]
I get the following error:

AEXML-1.3.1/AEXMLExample/ViewController.swift:27:38: Cannot invoke initializer for type 'AEXMLDocument' with an argument list of type '(xmlData: NSData, error: inout NSError?)' 

Any suggestions to what may be the issue?

**Comment by prasadpamidi** [comment]
AEXML v1.3.1 doesn't have support for Swift 2.0 yet. It doesn't seem like actively maintained

**Comment by nabil-takla** [comment]
Thanks @prasadpamidi. Which release supports Swift 2.0?

**Comment by tadija** [comment]
There is swift-2.0 branch which is currently up to date, but I want to do a few more things before releasing the official new version, so stay tuned, I hope it will be on master branch soon.

**Comment by nabil-takla** [comment]
Thanks @tadija. I'm looking forward to it!

**Comment by tadija** [comment]
Swift 2.0 support is now officially out in latest AEXML version 2.0.0.
