### ISSUE TITLE
Strange Compiler Bugs?

### ISSUE THREAD

**Issue by justinlevi** [tadija/AEXML#52]
I'm getting a really strange issue where the compiler is throwing a warning that a previous NSDictionary object is being automatically converted to an AEXMLElement. If I remove AEXML my code compiles fine. The model code in my screenshot below is not using AEXML at all. I've never seen this issue before and I'm wondering if this is a Swift 2.0 XCode 7.0 bug or something. 

![screen shot 2015-10-01 at 7 53 59 am](https://cloud.githubusercontent.com/assets/1117989/10220049/2f21f260-6812-11e5-9864-297d04401173.jpg)

**Comment by justinlevi** [comment]
Update - If I copy AEXML.swift into my project directly the issue goes away.

**Comment by tadija** [comment]
Hello, I've never had this kind of issue, so if you could create some sample project or playground which simulates this then I'll take a look.
