### ISSUE TITLE
How parse the tags using AEXML

### ISSUE THREAD

**Issue by YuvarajManic** [tadija/AEXML#54]
Hi Team,
Good Day!

Am familiar in XML Parsing using NSXMLParser in Objective-C. Now, am working in Swift I can use the NSXMLParser to parse the XML Response but, I have got suggestions to use third party framework (Library) to parse the xml content easily. I googled and found "AEXML" framework for SWIFT programming. I got confused to access the tags from "AEXMLElement". 

I have attached the sample response and my sample code for your reference.

I want to parse the main tag "item" and its sub tags "title", "link", "description", "author", "pubDate". How can I handle this?

Can you please help me to parse the xml files like this? 
Looking forward your help. Thank you.

Warm Regards,
Yuvaraj M

![screen shot 2015-10-06 at 7 15 38 pm](https://cloud.githubusercontent.com/assets/11453634/10310275/cc5c055c-6c5e-11e5-91a8-502aa7f73a7c.png)
![screen shot 2015-10-06 at 7 15 51 pm](https://cloud.githubusercontent.com/assets/11453634/10310276/cc60873a-6c5e-11e5-8b92-fbedd7a5030a.png)

**Comment by tadija** [comment]
Hello,

in your case each item is AEXMLElement which contains other elements which you can access like `item["title"].value` or `item["link"].value`.
