### ISSUE TITLE
"Cast from AEXMLElement to unrelated type ___ always fails"

### ISSUE THREAD

**Issue by aaronpk** [tadija/AEXML#57]
I'm not sure if this is somehow a problem with AEXML or a bug in XCode, or some other weird thing, so pardon me if it has nothing to do with this library.

Somehow, I'm getting an error on a file that doesn't use AEXML that there is a cast from AEXMLElement. If I comment out the `#import AEXML` line (in a totally unrelated file) then the project builds. Then when I uncomment the import, it builds fine.

I put together a simple sample project to illustrate this. 

https://github.com/aaronpk/AEXML_Test

**Comment by tadija** [comment]
Hello @aaronpk, 

I have looked into this problem, and I believe it's a possible bug on Apple side.

What I found out is that it's related to having custom subscript while inheriting from NSObject.

If you paste this code into Xcode Playground you'll see the same warning, but it will go away if you just remove inheritance from NSObject.

```swift
import Foundation

class ClassWithSubscript: NSObject {
    subscript(key: String) -> ClassWithSubscript {
        return self
    }
}

func testFunc(settings: Dictionary<String, AnyObject>) {
    if let nested = settings["foo"] {
        if let foo = nested["bar"] {
            print(foo as! Int)
        }
    }
}
```

What do you think? Should we report this as a bug?

**Comment by JerrySievert** [comment]
i think it should be reported as a bug - the interesting thing is that it occurs in both 7.0 and 7.1 (swift 2 and 2.1).

**Comment by gabek** [comment]
Any updates on this?  I run into this simply using subscript on a dictionary object, not even a custom class of mine.

**Comment by jmagnini** [comment]
I am having an issue with this as well.  Has anybody found a suitable workaround?

**Comment by tadija** [comment]
Ok, so I just reported this bug to Apple. ID: 23694764

**Comment by gabek** [comment]
I'm just going through and changing all of my [subscript] syntaxes to .valueForKey to work around it.

**Comment by deepakmishra11** [comment]
Well i was also facing this issue, but then i was using Cocoapods. 
Later i added the library manually and the issue was gone automatically.
I guess that something is wrong when we use it as a framework(please back me up if m right, otherwise enlightening is appreciated)

**Comment by tadija** [comment]
So, without some real solution from Apple (this bug is still open), I removed inheritance from NSObject which in fact fixed this warning, so this issue can be closed now.
