### ISSUE TITLE
Marshalling data

### ISSUE THREAD

**Issue by Twelve57** [tadija/AEXML#58]
Hi !

I wonder if there is a way to bind the data with xml.
I mean, create a model class then bind the data by using a xml file.

I know that it's possible on Android, but i'm new to IOS :/

It's possible ?

Or if you have an other way to do it, because my models are complex and I can't bind the data by me self.

**Comment by tadija** [comment]
Sorry, that's not a job for XML parser, you should implement that logic yourself.

**Comment by karthick229** [comment]
Is It possible any project for Aexml with android....

**Comment by karthick229** [comment]
Hi guyz is there any project for Aexml with android...
