### ISSUE TITLE
AEXMLElement writes attributes unescaped

### ISSUE THREAD

**Issue by jonnermut** [tadija/AEXML#61]
I am using an old version, but I think this is still in the source - if you set an attribute value to a string with an & in it, it is written unescaped by .xmlString

**Comment by tyczj** [comment]
I see this problem too

**Comment by tadija** [comment]
Can you elaborate on this? Which version are you using? I'm only interested if it's the latest, and if you could please add some example in Xcode Playground perhaps?

**Comment by ferrarop** [comment]
It happens in the latest version.
It seems that you correctly escape the element "value", but not the attributes.

In particular, in the xmlString property, you use _\\(escapedStringValue)_ for the element value, but just _\\(value)_ for the attributes.

Attributes are _[String: String]_, so they can't access the _escapedStringValue_ property of _AEXMLElement_.
I think you should escape attributes in the same way you do for element values, doing something similar to the _escapedStringValue_ property.

    /// Complete hierarchy of `self` and `children` in **XML** escaped and formatted String
    public var xmlString: String {
        var xml = String()
        
        // open element
        xml += indentation(parentsCount - 1)
        xml += "<\(name)"
        
        if attributes.count > 0 {
            // insert attributes
            for (key, value) in attributes {
                xml += " \(key)=\"\(value)\""
            }
        }
        
        if value == nil && children.count == 0 {
            // close element
            xml += " />"
        } else {
            if children.count > 0 {
                // add children
                xml += ">\n"
                for child in children {
                    xml += "\(child.xmlString)\n"
                }
                // add indentation
                xml += indentation(parentsCount - 1)
                xml += "</\(name)>"
            } else {
                // insert string value and close element
                xml += ">\(escapedStringValue)</\(name)>"
            }
        }
        
        return

**Comment by tadija** [comment]
Hi, escaping attribute values is added in latest version (3.0.0). Thanks for reporting this!
