### ISSUE TITLE
Subscript Returns Error String as Value of AEXMLElement is Surprising (To Me)

### ISSUE THREAD

**Issue by bhendersonizeni** [tadija/AEXML#62]
It cramps my style. :smile_cat: It also feels awkward having to type:

```
let element = elementList["MyElement"]
if element.name != AEXMLElement.errorElementName {
    let string = element["MyString"].stringValue
}
```

as opposed to something like:

```
let element = elementList["MyElement"]
let string = element["MyString"].stringValue // I would expect string == ""
```

because 99% of the time I don't want the string, `"element <MyString> not found"`, because I use `stringValue`. Was under the assumption that `stringValue` would return an empty string upon lookup error, not an error string.

This is coming from having used SwiftyJSON. So that is where my expectations are coming from. Feel free to disagree if that's how you feel.

Thoughts?

**Comment by tadija** [comment]
Hmmm, I think I agree. :)
This will be left open for now, maybe I'll change that in some upcoming version.

**Comment by ivensdenner** [comment]
What about the subscript returning a optional type? It sounds more natural to me.

**Comment by tadija** [comment]
No, that's what I wanted to avoid from the initial version. It's easier for end users when subscript is not an optional. And problem with empty string is that you couldn't differentiate when something really has no value or the complete element is missing.

**Comment by strongwillow** [comment]
I kind of agree @ivensdenner. My preferred usage is:

    if let v = element["MyString"] {
        print(v.stringValue)
    }

**Comment by Stitch7** [comment]
Helped myself with:

```swift
extension AEXMLElement {
    var string: String? {
        if name == AEXMLElement.errorElementName { return nil }
        return stringValue
    }
}
```

**Comment by cbh2000** [comment]
In SwiftyJSON, there are two getters: `var string: String?` and `var stringValue: String`. The equivalent of SwiftyJSON's `var string: String?` is AEXMLElement's `var value: String?`. AEXMLElement can be made to mimic SwiftyJSON if subclassed like below:

```
class MyAEXMLElement: AEXMLElement {
    var value: String? {
        guard name != AEXMLElement.errorElement else {
            return nil
        }
        return value
    }

    override var stringValue: String {
        guard name != AEXMLElement.errorElement else {
            return ""
        }
        return super.stringValue
    }
}
```

And SwiftyJSON handles the errors by having an explicit `var error: NSError?` property, in case you want the actual error:

```
extension MyAEXMLElement {
    var error: NSError? {
        guard let value = value where name == AEXMLElement.errorElement else {
            return nil
        }
        return convertToNSError(value)
    }
}
```

Of course, I'm not saying the above is _exactly_ how I think it should be implemented. I'm only showing how I would _adapt_ the existing code to behave like SwiftyJSON.

**Comment by tadija** [comment]
Hi all, thanks for this discussion.

In the latest version (3.0.0) I've improved error handling logic to be as you recommended here, that is:
- there is no `errorElementName` anymore
- subscript returns empty element (value = nil and stringValue = "")
- this empty element will have `error` property different then nil

Feel free to comment this change if you find anything suspicious (unit tests are passing but this can make breaking changes in other people code, that's why it's a major version bump).

This issue can be closed now.
