### ISSUE TITLE
Carthage: Problem during build of watchOS and tvOS

### ISSUE THREAD

**Issue by innoreq** [tadija/AEXML#64]
For me it's not possible to perform a ```carthage update```, an error is thrown:
```Swift
** BUILD FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
A shell task failed with exit code 65:
** BUILD FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
```

A selective build of iOS and Mac only is working fine.

**Comment by tadija** [comment]
Can you confirm it's AEXML that's failing?

I can build project normally for all platforms.

**Comment by innoreq** [comment]
Yes, I installed Carthage as instructed, added AEXML to the Cartfile, tried to perform a Carthage update, and that fails completely because of tvOS and watchOS.

When doing a selective update for iOS and OSX only, then it’s working fine.

**Comment by tadija** [comment]
Hi, this should be fixed now, thanks for reporting.
