### ISSUE TITLE
Parsing Element within Another element loses the value of the first Element

### ISSUE THREAD

**Issue by willchen** [tadija/AEXML#68]
I'm submitting a new bug related to #66.  I responded to your response, but I didn't see anything after that.

Below is my response:

Sorry, I missed escaping opening the \<STAGEDIR> in the previous comment.

Below is the XML that is valid and AEXML was not correctly taking in.

\<SPEECH>
    \<SPEAKER>SAMPSON\</SPEAKER>
    \<LINE>\<STAGEDIR>Aside to GREGORY\</STAGEDIR>  Is the law of our side, if I say\</LINE>
    \<LINE>ay?\</LINE>
\</SPEECH>

**Comment by tadija** [comment]
Sorry, I forgot to reopen #66, which I did now, so I'll close this one instead.
