### ISSUE TITLE
Module file was created by an older version of the compiler rebuild and try again

### ISSUE THREAD

**Issue by Jon-W-09** [tadija/AEXML#72]
Using Xcode 7.3 with target deployment set to iOS 9.3 (using pods) I'm seeing the error:

> Module file was created by an older version of the compiler; rebuild 'AEXML' and try again...

Are there any plans to address this incompatibility with the latest version of the compiler please?

**Comment by tadija** [comment]
Yes, as soon as I have time for that. In the meantime you can lower your deployment target to 9.0 perhaps?

**Comment by Jon-W-09** [comment]
Thanks. I just tried that, however it seems that the issue is to do with the version of Xcode. I suspect reverting back to Xcode 7.2 or earlier would allow the code to compile (I haven't tried this yet).

**Comment by tadija** [comment]
Hi, this should be fixed now, thanks for reporting.
