### ISSUE TITLE
Swift 3 Update

### ISSUE THREAD

**Issue by gabriel-jones** [tadija/AEXML#73]
Swift 3 will have some deprecated features that are in AEXML:

[Removal of '++' and '--' operators'](https://github.com/apple/swift-evolution/blob/master/proposals/0004-remove-pre-post-inc-decrement.md), [removal of 'var parameters'](https://github.com/apple/swift-evolution/blob/master/proposals/0003-remove-var-parameters.md)

I found deprecation warnings on lines 229, 225, 219, and 167. These should be fixed before Swift 3 is released

**Comment by appsird** [comment]
I also receive a warning "var' parameters are deprecated and will be removed in Swift 3 on line 226:

    private func indentation(var count: Int) -> String {

**Comment by tadija** [comment]
Hi, this is fixed now, thanks for reporting!
