### ISSUE TITLE
Swift 3 Support

### ISSUE THREAD

**Issue by appsird** [tadija/AEXML#79]
Hi,

I installed the latest Xcode with Swift 3.0, and AEXML generates numerous errors. Would appreciate a new release which supports. 

Thanks much,
Brian.

**Comment by franklinyu** [comment]
[My fork](https://github.com/franklinyu/AEXML) should support Swift 3.0; use tag `3.0.0`.

**Comment by franklinyu** [comment]
I installed the Xcode beta with Swift 3.0 as well. Swift 3 is incompatible with Swift 2 (we cannot write a library that works in both environment. Currently I am working to convert it to provide Swift 3.0 support elsewhere. You can also try [this branch](https://github.com/raumfeld/AEXML/tree/swift3) from @raumfeld.

**Comment by franklinyu** [comment]
Ok I finished my work. Add this to your `dependencies` to use it:

```
.Package(url: "https://github.com/franklinyu/AEXML.git", Version(stringLiteral: "3.0.0-rc1"))
```

This seems long because it is still a release candidate. Once stable Swift 3 is released, I will bump to 3.0.0 and this will work:

```
.Package(url: "https://github.com/franklinyu/AEXML.git", majorVersion: 3)
```

**Comment by michaellindahl** [comment]
Rather than asking users to point to @franklinyu's fork, can we create a branch on @tadija's repository for swift3 support?

**Comment by franklinyu** [comment]
@michaellindahl That would be the best, after @tadija decides to fully migrate to Swift 3. I guess he is waiting for Swift 3 to be stable (probably this fall).

**Comment by appsird** [comment]
I attached a version which is Swift 3 and iOS10 compatible. NSXMLParser became XMLParser, and other changes.

[AEXML.swift.zip](https://github.com/tadija/AEXML/files/345138/AEXML.swift.zip)

**Comment by appsird** [comment]
The new iOS10 beta 6 hs new issues, specifically with property:

public private(set) children [AEXMLElement] = [AEXMLElement]()

Has anyone else tried beta 6 as yet. I can upload my AEXML image or if a branch could be created...

To date I was able to workaround other issues, though this one's a showstopper.

**Comment by appsird** [comment]
Update:

I was able to workaround by dropping the 'private(set) and some other tweaks; I will upload .zip file later today for others to use in the interim.

**Comment by franklinyu** [comment]
There are already two pull requests for it: #77 and #84.

**Comment by appsird** [comment]
ok, thanks.

**Comment by lightbow** [comment]
@tadija is this project still active?

**Comment by appsird** [comment]
If you require ios10 support check the two pulls recommended by franklinyu. Original author waiting for swift 3 dust to settle

**Comment by tadija** [comment]
Hey people, sorry because it took me so long, but Swift 3 support is finally here in AEXML 4.0.0, and thanks all for your help in this 'waiting' period!

**Comment by wmorgan6796** [comment]
Is there a reason xcode is still asking me to convert AEXML 4.0.0 to swift 3?

**Comment by franklinyu** [comment]
My Xcode 8.0 (8A218a) on El Capitan does not ask me to do any conversion.

**Comment by TahiG** [comment]
Hi all, 

I've followed the above, replaced my AEXML.swift file with the one posted by appsird above and I'm still getting errors (pictured). New to development so would appreciate layman's terms and simplified suggestions.

I'm updating my Swift 2.3 source code after being forced to convert it by Xcode. Now running Swift 3 or 4 (not sure) on Xcode 8.3.3. 

Thanks for your help!

![screen shot 2017-11-06 at 23 29 59](https://user-images.githubusercontent.com/22755405/32469506-f2686cfa-c34a-11e7-90b5-e39ac5be60df.png)

**Comment by franklinyu** [comment]
@TahiG Which version of AEXML are you using? [Latest version](https://github.com/tadija/AEXML/tree/4.1.0/Sources) doesn't seem to have the file `AEXML.swift`.

**Comment by TahiG** [comment]
Hi Franklinyu,

I did a pod install of the latest FolioReader which installed AEXML with it. When all the AEXML-related errors popped up I downloaded the zip file by appsird (above): https://github.com/tadija/AEXML/files/345138/AEXML.swift.zip and replaced the existing AEXML.swift with this one. There were fewer errors but largely the same. Any suggestions?

**Comment by franklinyu** [comment]
@TahiG That is super weird. Latest FolioReader [requires AEXML 4.0 onward](https://github.com/FolioReader/FolioReaderKit/blob/1.2.0/FolioReaderKit.podspec#L35) which does not have `AEXML.swift`. Would you like to check your `Podfile.lock`? If you have difficulty understand the `Podfile.lock` syntax, I'm glad to help.

In addition, latest AEXML already support Swift 3.0. There should be no need to use the version by appsird (which I don't think is maintained by anyone, not even himself).

**Comment by TahiG** [comment]
Yes, If you could tell me what to look for in the podfile.lock that would be awesome. I assume any text editor will open?

**Comment by franklinyu** [comment]
Yes. It's plain text. There should be a line with `AEXML (4.0.0)` or something similar.

**Comment by TahiG** [comment]
Thanks Franklinyu, it turned out I had FolioReader v0.94 and AEXML v3.0.0 so I updated FolioReader to v1.2.0 and AEXML to v4.0 by manually downloading the zips from Github (as opposed to using Terminal) and now when I build there's just one error that reads:

<unknown>:0: error: no such file or directory: '/Users/Destina/Downloads/globe-app-code 2/Pods/AEXML/Sources/AEXML.swift'
Command/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc failed with exit code 1

I've tried searching for answers but most just say cleaning works for them. Unfortunately its not working for me.

**Comment by franklinyu** [comment]
Is there any other dependencies that you don't want to upgrade? If you feels lucky, maybe you can just `pod update` and everything will be latest. Then try cleaning and rebuild everything. (It's a good idea to keep everything latest anyway.)

**Comment by TahiG** [comment]
I've tried `pod update` , cleaning and rebuilding but still getting multiple errors:

![screen shot 2017-11-08 at 14 26 43](https://user-images.githubusercontent.com/22755405/32554199-e76396da-c490-11e7-9a41-0957f2ccbab3.png)

Any advice would be appreciated.

**Comment by franklinyu** [comment]
@TahiG Among the errors in this case, is there any one related to AEXML? If the errors are related to FolioReader, then their developers may give better advice.

**Comment by williampenna** [comment]
@franklinyu I'm trying to import AEXML on my Swift 4 Xcode 9.2, but it's giving an error.
Could you help me?
The error is this: "Value of type '[AEXMLElement]' has no member 'compactMap'"
Thank you in advance!

**Comment by williampenna** [comment]
Ok, I'll have to update Xcode even, so I'll update and test with 4.3.0 version. Thank very much for the answer.
