### ISSUE TITLE
How to build XML like this? Google earth KML file that has multiple coordinates

### ISSUE THREAD

**Issue by callagga** [tadija/AEXML#81]
Here is an excert.  Wondering how to create the XML programmatically for this?  It's basically multiple lines of "Lat/Long/Altitude"?

      <LineString>
        <extrude>1</extrude>
        <tessellate>1</tessellate>
        <altitudeMode>absolute</altitudeMode>
        <coordinates> -112.2550785337791,36.07954952145647,2357
          -112.2549277039738,36.08117083492122,2357
          -112.2552505069063,36.08260761307279,2357
          -112.2564540158376,36.08395660588506,2357
          -112.2580238976449,36.08511401044813,2357
          -112.2595218489022,36.08584355239394,2357
          -112.2608216347552,36.08612634548589,2357
          -112.262073428656,36.08626019085147,2357
          -112.2633204928495,36.08621519860091,2357
          -112.2644963846444,36.08627897945274,2357
          -112.2656969554589,36.08649599090644,2357 
        </coordinates>
      </LineString>

**Comment by ivensdenner** [comment]
You can try this:

```
for coordinateString in coordinatesStrings {
    coordinatesElement.value += coordinateString + "\n"
}
```

Where `coordinatesElement is AEXMLElement`.

**Comment by franklinyu** [comment]
If you design the schema yourself, I would suggest design it this way:

```xml
<coordinates>
  <coordinate>
    <latitude>-112.2550785337791</latitude>
    <longitude>36.07954952145647</longitude>
    <altitude>2357</altitude>
  </coordinate>
  <coordinate>
    <latitude>-112.2549277039738</latitude>
    <longitude>36.08117083492122</longitude>
    <altitude>2357</altitude>
  </coordinate>
</coordinates>
```

**Comment by tadija** [comment]
Thanks @ivensdenner, I hope that works for you @callagga, I'll close this issue.
