### ISSUE TITLE
Read XML 

### ISSUE THREAD

**Issue by vre142** [tadija/AEXML#83]
Hi I have this xml code:

<Actions><Action ActionName=\'ارائه پيشرائه پيش\331نهاد و نظر\' ActionCode=\'2\'  IsSign=\'0\'  FarsiDescription=\'\'  IsActiveForCartable=\'1\'  IsActiveForSend=\'1\'  /><Action ActionName=\'مشاهده و رونوشت\' ActionCode=\'3\'  IsSign=\'0\'  FarsiDescription=\'\'  IsActiveForCartable=\'1\'  IsActiveForSend=\'1\'  /><Action ActionName=\'يادآوري\' ActionCode=\'5\'  IsSign=\'0\'  FarsiDescription=\'\'  IsActiveForCartable=\'1\'  IsActiveForSend=\'1\'  /><Action ActionName=\'بايگاني\' ActionCode=\'6\'  IsSign=\'0\'  FarsiDescription=\'\'  IsActiveForCartable=\'0\'  IsActiveForSend=\'1\'  /><Action ActionName=\'ثبت وارده\' ActionCode=\'7\'  IsSign=\'0\'  FarsiDescription=\'\'  IsActiveForCartable=\'0\'  IsActiveForSend=\'0\'  /><Action ActionName=\'ثبت صادره\' ActionCode=\'8\'  IsSign=\'0\'  FarsiDescription=\'\'  IsActiveForCartable=\'0\'  IsActiveForSend=\'1\'  /><Action ActionName=\'ساير اعمال\' ActionCode=\'9\'  IsSign=\'0\'  FarsiDescription=\'\'  IsActiveForCartable=\'1\'  IsActiveForSend=\'1\'  /><Action ActionName=\'استحضار\' ActionCode=\'1004\'  IsSign=\'0\'  FarsiDescription=\'\'  IsActiveForCartable=\'1\'  IsActiveForSend=\'1\'  /><Action ActionName=\'ارجاع اع \330از دبيرخانه\' ActionCode=\'10\'  IsSign=\'0\'  FarsiDescription=\'\'  IsActiveForCartable=\'1\'  IsActiveForSend=\'1\'  /><Action ActionName=\'درخواست جلسه\' ActionCode=\'11\'  IsSign=\'0\'  FarsiDescription=\'\'  IsActiveForCartable=\'1\'  IsActiveForSend=\'1\'  /><Action ActionName=\'گردش كار متمركز\' ActionCode=\'12\'  IsSign=\'0\'  FarsiDescription=\'\'  IsActiveForCartable=\'0\'  IsActiveForSend=\'0\'  /><Action ActionName=\'جهت اقدام\' ActionCode=\'13\'  IsSign=\'0\'  FarsiDescription=\'\'  IsActiveForCartable=\'1\'  IsActiveForSend=\'1\'  /><Action ActionName=\'ارجاع به خارج از سازمان\' ActionCode=\'1002\'  IsSign=\'0\'  FarsiDescription=\'\'  IsActiveForCartable=\'0\'  IsActiveForSend=\'0\'  /><Action ActionName=\'امضاء\' ActionCode=\'1\'  IsSign=\'1\'  FarsiDescription=\'\'  IsActiveForCartable=\'1\'  IsActiveForSend=\'1\'  /><Action ActionName=\'امضاء\' ActionCode=\'1003\'  IsSign=\'0\'  FarsiDescription=\'ارجاع به بيرون از سازمان\'  IsActiveForCartable=\'0\'  IsActiveForSend=\'0\'  /></Actions> 

 but I can't read and parse it with your library can you help me about my problem?
THanks
Vafa

**Comment by fredpi** [comment]
👎

**Comment by tadija** [comment]
Sorry, not enough details here.
