### ISSUE TITLE
Parsing OSM

### ISSUE THREAD

**Issue by vt45** [tadija/AEXML#89]
Hi,
When parsing openSreetMap data I can't find the way to get all the content of the attributes when there are more than 2 children from root. It only iterates once. I have attached a small sample of the data. I'm working with a big file. (xml attached with .txt extension)

```
for nodes in xmlDoc.root["nodes"]["node"].all!{
    if let id = nodes.attributes["id"] {
        Swift.print(id)
    }        
}

for nd in xmlDoc.root["ways"]["way"]["nd"].all! {
    if let ref = nd.attributes["ref"] {
        Swift.print(ref)
    }
}
```

The first for loop gives all the "id"s in all "nodes"
The second for loop gives only the first <nd>s in <way> but should be getting all the <nd>s ?

Thanks for your help.

[map.txt](https://github.com/tadija/AEXML/files/471596/map.txt)

**Comment by tadija** [comment]
Hi,

the second loop would return all "nd" elements from the first "way" element in "ways".
You probably wanted to iterate all "way" elements so you need to have some nested loops,
like `for way in xmlDoc.root["ways"]["way"].all! { // another loop for all "nd" elements here... }`.

Cheers
