### ISSUE TITLE
Swift 3

### ISSUE THREAD

**Issue by kerbelda** [tadija/AEXML#92]
Keep getting the error" Module compiled with Swift 2.3 cannot be imported in Swift 3.0" in Xcode 8. I tried setting the Use Legacy Swift Language Version flag to No in the AEXML target, but then I get a ton of errors. One, for example, is AEXMLDocument being an unresolved identifier.

How do I use this with Swift 3?

**Comment by tadija** [comment]
Hi, please try with the fix of latest version 4.0.1. from #91 and let me know if that works for you.

**Comment by NaveenCykul** [comment]
Hi, I am getting error as Use of unresolved identifier 'AEXMLDocument'. how do i resolve it 
i installed pods still am getting error.
and how do I use in swift 4
