### ISSUE TITLE
How to update Attribute of existing child attribute

### ISSUE THREAD

**Issue by nitisha1** [tadija/AEXML#93]
Hi,
i've updated AEXML framework in my project in xcode8 to support for Swift3.I want to update existing child attribute but cannot find replacement of method
`func addAttribute(name: NSObject, value: AnyObject)`
Any help please?

**Comment by tadija** [comment]
Hi, that method was removed in [this commit](https://github.com/tadija/AEXML/commit/ff497577f52a40b618175b722d1b4c20a283e8ea) because you can now do that directly with `attributes` property.
