### ISSUE TITLE
Build problem

### ISSUE THREAD

**Issue by breferrari** [tadija/AEXML#96]
I'm having a problem that happens every second run related to AEXML

`Failed to load Info.plist from bundle at path /Users/brennoferrari/Library/Developer/CoreSimulator/Devices/D934DF7D-B118-48CC-8327-107482FEBA3C/data/Library/Caches/com.apple.mobile.installd.staging/temp.yN5gVn/extracted/Payload/ampm.app/Frameworks/AEXML.framework`

Does anyone have this problem or know how to fix it? I can only run again if I clean the project everytime this happens.

**Comment by tadija** [comment]
I'm not sure how this happens to you, have you tried product/clean, remove derrived data, restart xcode etc? It seems to me like it was a temporary issue so I'll close this one.
