### ISSUE TITLE
Parse a stored xml string ?

### ISSUE THREAD

**Issue by Kishou** [tadija/AEXML#97]
Hi ,
your AEXML is great for generating XML string, but how can i do parse the XML String again that is stored in a variable using your library ?
I can't seem to find the way or solution  from your documentation, since all of them are getting XML from a file or url.

**Comment by ivensdenner** [comment]
The [Document](https://github.com/tadija/AEXML/blob/master/Sources/Document.swift) class has the following convenience initializer:

`convenience init(xml: String, encoding: String.Encoding, options: AEXMLOptions) throws`

I think it does exactly what you want.

**Comment by Kishou** [comment]
in which version exactly that the feature exists ? it seems like in version 2.1.0 that i am using for swift 2 doesn't has that kind of function at all.

**Comment by ivensdenner** [comment]
Yeah, I think it wasn't there yet in the version you're using. But yet you have the following initializer in 2.1.0:

```swift
convenience init(version: Double = Defaults.version,
                 encoding: String = Defaults.encoding,
                 standalone: String = Defaults.standalone,
                 xmlData: NSData,
                 xmlParserOptions: NSXMLParserOptions = NSXMLParserOptions()) throws
```

And you can easily get the data from a string using:

```swift
let data = string.dataUsingEncoding(NSUTF8StringEncoding)
```

But `string` must be a instance of `NSString`.

Therefore, you can get the data from the string and use the initializer mentioned above.

**Comment by Kishou** [comment]
i see, quite a long one but will take longer if use native instead of your library
haha
thanks !
i'll try that
