### ISSUE TITLE
Remove declaration from SOAP request

### ISSUE THREAD

**Issue by gsolanki1509** [tadija/AEXML#98]
First of all, the library is very good. Thanks..!!

My desired SOAP request:

<x:Envelope xmlns:x="http://schemas.xmlsoap.org/soap/envelope/" xmlns:cif="http://www.mawarid.ae/linkedCardsSummary/CRM/CIF.xsd">
	<x:Header />
	<x:Body>
		<cif:CIFReq>
			<cif:CIFNo>000000196</cif:CIFNo>
		</cif:CIFReq>
	</x:Body>
</x:Envelope>

Below is my code to create SOAP request:

let soapRequest = AEXMLDocument()
        let attributes = ["xmlns:x" : "http://schemas.xmlsoap.org/soap/envelope/", "xmlns:cif" : "http://www.mawarid.ae/linkedCardsSummary/CRM/CIF.xsd"]
        let envelope = soapRequest.addChild(name: "x:Envelope", attributes: attributes)
        let header = envelope.addChild(name: "x:Header")
        let body = envelope.addChild(name: "x:Body")
        let getStockPrice = body.addChild(name: "cif:CIFReq")
        getStockPrice.addChild(name: "cif:CIFNo", value: "000000196")

And by Output is:
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<x:Envelope xmlns:x="http://schemas.xmlsoap.org/soap/envelope/" xmlns:cif="http://www.mawarid.ae/linkedCardsSummary/CRM/CIF.xsd">
	<x:Header />
	<x:Body>
		<cif:CIFReq>
			<cif:CIFNo>000000196</cif:CIFNo>
		</cif:CIFReq>
	</x:Body>
</x:Envelope>

But i want to remove declaration i.e. "<?xml version="1.0" encoding="utf-8" standalone="no"?>" .

Please help me

**Comment by tadija** [comment]
Hi,

I'm not sure how (or why) could you do that, 
but it seems to me from looking at the desired and output requests here that those are identical, 
so because of that I don't quite understand the problem behind?

Cheers
